# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: {{ .Values.frontend.appName }}
#   name: {{ .Values.frontend.appName }}
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: {{ .Values.frontend.appName }}
#   template:
#     metadata:
#       labels:
#         app: {{ .Values.frontend.appName }}
#         tier: proxy
#     spec:
#       containers:
#       - name: apache
#         image: registry.access.redhat.com/ubi8/httpd-24:1-226
#         ports:
#         - containerPort: 8080
#           name: http
#           protocol: TCP
#         volumeMounts:
#         - mountPath: /var/www/html
#           name: {{ .Values.frontend.appName }}-configmap
#         env:
#         - name: API_URL
#           value: 'echo-backend.test.svc.cluster.local:5002/api'
#       - name: proxy
#         image: {{ .Values.frontendProxy.imageName }}
#         ports:
#         - containerPort: {{ .Values.frontendProxy.port }}
#         env:
#         - name: API_URL
#           value: 'http://echo-backend.test.svc.cluster.local:5002'
#       volumes:
#       - name: {{ .Values.frontend.appName }}-configmap
#         configMap:
#           name: {{ .Values.frontend.appName }}-configmap
#           defaultMode: 0777

