apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.frontend.appName }}
  name: {{ .Values.frontend.appName }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8081-tcp
    port: 8081
    targetPort: 8081
  selector:
    app: {{ .Values.frontend.appName }}
    # deploymentconfig: {{ .Values.frontend.appName }}
  # sessionAffinity: None
  # type: ClusterIP


