apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend-proxy.appName }}
spec:
  selector:
    app: {{ .Values.frontend-proxy.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend-proxy.port }}
      targetPort: {{ .Values.frontend-proxy.port }}
    selector:
      app: {{ .Values.frontend-proxy.appName }}
      tier: proxy
