apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.frontend.appName }}
  name: {{ .Values.frontend.appName }}
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: {{ .Values.frontend.appName }}
    weight: 100
  wildcardPolicy: None
  tls:
    insecureEdgeTerminationPolicy: Redirect
