apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.echoapi.appName }}
spec:
  ports:
  - name: {{ .Values.echoapi.appName }}-port
    port: {{ .Values.echoapi.port }}
    protocol: TCP
    targetPort: {{ .Values.echoapi.port }}
  selector:
    app: {{ .Values.echoapi.appName }}
  type: ClusterIP