apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  audit:
    logLevel: INFO
    replicas: 1
  mutatingWebhook: Enabled
  validatingWebhook: Enabled
  webhook:
    admissionEventsInvolvedNamespace: Enabled
    emitAdmissionEvents: Enabled
    logLevel: DEBUG
    logMutations: Enabled
    mutationAnnotations: Enabled
    replicas: 1