apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.global.applicationName }}
  name: {{ .Values.global.applicationName }}
spec:
  replicas: 1
  strategy:
    activeDeadline: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 120
      updatePeriodSeconds: 1
    type: Rolling
  selector:
    matchLabels:
      app: {{ .Values.global.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.applicationName }}
    spec:  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30 
  containers:
    - image: {{.Values.global.imageRegistry }}/{{ .Values.global.applicationName }}:{{ .Values.global.environment }}
      imagePullPolicy: Always
      name: {{ .Values.global.applicationName }}
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          memory: 64Mi
          cpu: 250
        limits:
          memory: 128
          cpu: 500m    
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      env:
        - name: TZ
          value: America/Toronto
        - name: mcg.database
          valueFrom:
            secretKeyRef:
              key: database
              name: mcg-rds-secret-basic-auth
        - name: mcg.host
          valueFrom:
            secretKeyRef:
              key: host
              name: mcg-rds-secret-basic-auth
        - name: mcg.port
          valueFrom:
            secretKeyRef:
              key: port
              name: mcg-rds-secret-basic-auth
        - name: mcg.username
          valueFrom:
            secretKeyRef:
              key: username
              name: mcg-rds-secret-basic-auth
        - name: mcg.password
          valueFrom:
            secretKeyRef:
              key: password
              name: mcg-rds-secret-basic-auth
        - name: GeocodingAPIKey
          valueFrom:
            secretKeyRef:
              key: GeocodingAPIKey
              name: mcg-rds-secret-basic-auth